name: cos_challenge
description: "COS Flutter Challenge"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Network
  http: ^1.4.0

  # Dependency Injection
  get_it: ^8.0.3
  equatable: ^2.0.7
  injectable: ^2.5.0

  # Local Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.15
  injectable_generator: ^2.6.2

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
